name: Build Latest Docker Image

on:
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
          - final
  
jobs:
  build-and-push:
    name: Build image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout source code
    - name: Build the Docker image
      run: |
        docker build . --tag synbiohub/sbolcanvas:latest